---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - include_vars: vars/vm_variables.yml
    - name: Create a virtual machine on given ESXi hostname
      community.vmware.vmware_guest:
        hostname: "{{ esxi_server }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: /
        name: "{{ vm_name }}"
        state: "{{ vm_power_state }}"
        guest_id: "{{ vm_guest_id }}"       
        disk:
        - size_gb: "{{ vm_disk_size }}"
          type: "{{ vm_disk_type }}"
          datastore: "{{ vm_datastore }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpu }}"
          scsi: paravirtual
        networks:
        - name: VM Network
          connected: yes    
      delegate_to: localhost
      register: deploy_vm
    - debug: 
        msg: "{{ deploy_vm }}"